kind: source
spec:
  name: "aws"
  path: cloudquery/aws
  registry: cloudquery
  version: v26.10.0
  destinations: ["postgresql"]
  tables: ["*s3_bucket*"]
  spec: 
    accounts:
      - id: "615713231484"
---
kind: destination
spec:
  name: "postgresql"
  path: cloudquery/postgresql
  registry: cloudquery
  version: v8.0.5
  write_mode: "overwrite-delete-stale" # overwrite-delete-stale, overwrite, append
  spec:
    connection_string: "postgresql://postgres:12345@localhost:5432/postgres?sslmode=disable"
---
kind: transform
spec:
  name: test
  path: /Users/alex/Developer/scratch/transform/main.wasm
